/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleriRouteImport } from './routes/galleri'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as PrislistaRouteImport } from './routes/prislista'
import { Route as TeametRouteImport } from './routes/teamet'
import { Route as TidsbokningRouteImport } from './routes/tidsbokning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriRoute = GalleriRouteImport.update({
  id: '/galleri',
  path: '/galleri',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrislistaRoute = PrislistaRouteImport.update({
  id: '/prislista',
  path: '/prislista',
  getParentRoute: () => rootRouteImport,
} as any)
const TeametRoute = TeametRouteImport.update({
  id: '/teamet',
  path: '/teamet',
  getParentRoute: () => rootRouteImport,
} as any)
const TidsbokningRoute = TidsbokningRouteImport.update({
  id: '/tidsbokning',
  path: '/tidsbokning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/prislista': typeof PrislistaRoute
  '/teamet': typeof TeametRoute
  '/tidsbokning': typeof TidsbokningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/prislista': typeof PrislistaRoute
  '/teamet': typeof TeametRoute
  '/tidsbokning': typeof TidsbokningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/prislista': typeof PrislistaRoute
  '/teamet': typeof TeametRoute
  '/tidsbokning': typeof TidsbokningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/galleri' | '/kontakt' | '/prislista' | '/teamet' | '/tidsbokning'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galleri' | '/kontakt' | '/prislista' | '/teamet' | '/tidsbokning'
  id:
    | '__root__'
    | '/'
    | '/galleri'
    | '/kontakt'
    | '/prislista'
    | '/teamet'
    | '/tidsbokning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleriRoute: typeof GalleriRoute
  KontaktRoute: typeof KontaktRoute
  PrislistaRoute: typeof PrislistaRoute
  TeametRoute: typeof TeametRoute
  TidsbokningRoute: typeof TidsbokningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleri': {
      id: '/galleri'
      path: '/galleri'
      fullPath: '/galleri'
      preLoaderRoute: typeof GalleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prislista': {
      id: '/prislista'
      path: '/prislista'
      fullPath: '/prislista'
      preLoaderRoute: typeof PrislistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teamet': {
      id: '/teamet'
      path: '/teamet'
      fullPath: '/teamet'
      preLoaderRoute: typeof TeametRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tidsbokning': {
      id: '/tidsbokning'
      path: '/tidsbokning'
      fullPath: '/tidsbokning'
      preLoaderRoute: typeof TidsbokningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleriRoute: GalleriRoute,
  KontaktRoute: KontaktRoute,
  PrislistaRoute: PrislistaRoute,
  TeametRoute: TeametRoute,
  TidsbokningRoute: TidsbokningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
