/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BokaRouteImport } from './routes/boka'
import { Route as GalleriRouteImport } from './routes/galleri'
import { Route as HittahitRouteImport } from './routes/hittahit'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as TeamRouteImport } from './routes/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BokaRoute = BokaRouteImport.update({
  id: '/boka',
  path: '/boka',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriRoute = GalleriRouteImport.update({
  id: '/galleri',
  path: '/galleri',
  getParentRoute: () => rootRouteImport,
} as any)
const HittahitRoute = HittahitRouteImport.update({
  id: '/hittahit',
  path: '/hittahit',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boka': typeof BokaRoute
  '/galleri': typeof GalleriRoute
  '/hittahit': typeof HittahitRoute
  '/priser': typeof PriserRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boka': typeof BokaRoute
  '/galleri': typeof GalleriRoute
  '/hittahit': typeof HittahitRoute
  '/priser': typeof PriserRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boka': typeof BokaRoute
  '/galleri': typeof GalleriRoute
  '/hittahit': typeof HittahitRoute
  '/priser': typeof PriserRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boka' | '/galleri' | '/hittahit' | '/priser' | '/team'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boka' | '/galleri' | '/hittahit' | '/priser' | '/team'
  id:
    '__root__' | '/' | '/boka' | '/galleri' | '/hittahit' | '/priser' | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BokaRoute: typeof BokaRoute
  GalleriRoute: typeof GalleriRoute
  HittahitRoute: typeof HittahitRoute
  PriserRoute: typeof PriserRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boka': {
      id: '/boka'
      path: '/boka'
      fullPath: '/boka'
      preLoaderRoute: typeof BokaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleri': {
      id: '/galleri'
      path: '/galleri'
      fullPath: '/galleri'
      preLoaderRoute: typeof GalleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hittahit': {
      id: '/hittahit'
      path: '/hittahit'
      fullPath: '/hittahit'
      preLoaderRoute: typeof HittahitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BokaRoute: BokaRoute,
  GalleriRoute: GalleriRoute,
  HittahitRoute: HittahitRoute,
  PriserRoute: PriserRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
